version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
        - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
